logs copied from google colab where network was trained

SIMPLE MODEL

Found 67692 files belonging to 131 classes.
Using 54154 files for training.
2022-11-13 17:36:46.390878: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
Found 67692 files belonging to 131 classes.
Using 13538 files for validation.
Found 22688 files belonging to 131 classes.
Epoch 1/10
/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)
847/847 [==============================] - 68s 77ms/step - loss: 3.2973 - accuracy: 0.2222 - val_loss: 1.8002 - val_accuracy: 0.5589
Epoch 2/10
847/847 [==============================] - 66s 77ms/step - loss: 1.2463 - accuracy: 0.6390 - val_loss: 0.8715 - val_accuracy: 0.7712
Epoch 3/10
847/847 [==============================] - 66s 78ms/step - loss: 0.6619 - accuracy: 0.8010 - val_loss: 0.5184 - val_accuracy: 0.8599
Epoch 4/10
847/847 [==============================] - 66s 77ms/step - loss: 0.4000 - accuracy: 0.8769 - val_loss: 0.3006 - val_accuracy: 0.9165
Epoch 5/10
847/847 [==============================] - 66s 78ms/step - loss: 0.2724 - accuracy: 0.9142 - val_loss: 0.2051 - val_accuracy: 0.9466
Epoch 6/10
847/847 [==============================] - 65s 77ms/step - loss: 0.1946 - accuracy: 0.9386 - val_loss: 0.1366 - val_accuracy: 0.9686
Epoch 7/10
847/847 [==============================] - 65s 77ms/step - loss: 0.1463 - accuracy: 0.9534 - val_loss: 0.0881 - val_accuracy: 0.9817
Epoch 8/10
847/847 [==============================] - 65s 76ms/step - loss: 0.1122 - accuracy: 0.9651 - val_loss: 0.0547 - val_accuracy: 0.9886
Epoch 9/10
847/847 [==============================] - 65s 76ms/step - loss: 0.0861 - accuracy: 0.9733 - val_loss: 0.0662 - val_accuracy: 0.9844
Epoch 10/10
847/847 [==============================] - 65s 76ms/step - loss: 0.0766 - accuracy: 0.9753 - val_loss: 0.0582 - val_accuracy: 0.9855
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 3 of 3). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 3 of 3). These functions will not be directly callable after loading.
355/355 [==============================] - 13s 36ms/step - loss: 0.3150 - accuracy: 0.9262
Model simple_model accuracy: 92.62%


TRANSFER LEARNING

Epoch 1/3
/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)
847/847 [==============================] - 80s 91ms/step - loss: 0.1965 - accuracy: 0.9609 - val_loss: 0.0015 - val_accuracy: 0.9999
Epoch 2/3
847/847 [==============================] - 76s 89ms/step - loss: 0.0025 - accuracy: 0.9995 - val_loss: 0.0015 - val_accuracy: 0.9999
Epoch 3/3
847/847 [==============================] - 76s 90ms/step - loss: 0.0015 - accuracy: 0.9997 - val_loss: 0.0011 - val_accuracy: 0.9999
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 52). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 52). These functions will not be directly callable after loading.
355/355 [==============================] - 41s 115ms/step - loss: 0.0959 - accuracy: 0.9749
Model transfer_learning accuracy: 97.49%


FINE TUNING

Epoch 1/5
/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)
847/847 [==============================] - 111s 126ms/step - loss: 0.2702 - accuracy: 0.9423 - val_loss: 0.0010 - val_accuracy: 0.9999
Epoch 2/5
847/847 [==============================] - 104s 122ms/step - loss: 0.0013 - accuracy: 0.9997 - val_loss: 6.4103e-04 - val_accuracy: 0.9999
Epoch 3/5
847/847 [==============================] - 104s 122ms/step - loss: 1.6486e-04 - accuracy: 0.9999 - val_loss: 6.9187e-04 - val_accuracy: 0.9999
Epoch 4/5
847/847 [==============================] - 104s 122ms/step - loss: 2.9537e-05 - accuracy: 1.0000 - val_loss: 6.7100e-04 - val_accuracy: 0.9999
Epoch 5/5
847/847 [==============================] - 104s 122ms/step - loss: 1.1837e-05 - accuracy: 1.0000 - val_loss: 7.0309e-04 - val_accuracy: 0.9999
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 52). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 52). These functions will not be directly callable after loading.
355/355 [==============================] - 27s 75ms/step - loss: 0.0524 - accuracy: 0.9882
Model fine_tuning accuracy: 98.82%
